### ISSUE TITLE
how is "fixed4 c" a fixed4 type?

### ISSUE THREAD

**Issue by Turtwiggy** [smoothslerp/diffused-posterization#1]
Hey, firstly thanks for the blogs, love the content. 

As for the issue, not sure where to raise this, but just looking through and picking an issue with one of the lines.

`fixed4 c = (1-bar) * post + bar * (post+invK);`

As far as I'm aware, bar, post, and invK are all floats, how is this converted to a fixed4? Is this some unity wizardry?

<img src="https://user-images.githubusercontent.com/15272027/112222165-45a1b600-8c20-11eb-806b-8036779a5c16.png" width="500" height="300">

**Comment by smoothslerp** [comment]
Hello! This is a mistake on the blog that I will fix. The  code on github is correct. Thanks for pointing it out! Glad you like the site.

**Comment by smoothslerp** [comment]
Hello again, 

I took another look at your question and realized that not only is this not a mistake on the blog but also I didn't answer your actual question. Sorry about that! 

So here it goes: `(1-bar) * post + bar * (post+invK)` evaluates to a `fixed` type. When we assign a `fixed` to a `fixed4`, we are implicitly converting it such that all 4 components of the `fixed4 c` variable take on the same value.

For example: `fixed4 c = 1.0` is the same as doing `fixed4 c = fixed4(1.0, 1.0, 1.0, 1.0)`. 

In this section of the guide we are trying to visualize the color correction in grayscale and the implicit conversion allows us to do precisely that. As you see 3 lines later we assign `c.rgb` to the output color of the shader. This means that we are extracting the first 3 components of `fixed4 c` and assigning to `o.Albedo`.

Another way to do this could have been: 

```
fixed b = (1-bar) * post + bar * (post+invK);
. . . 
o.Albedo = b;

``` 
This would have been an implicit conversion from `fixed` to `fixed3` and would give us the same result and would have perhaps been simpler!

I hope that helps and if you have any other questions about this or any other project raising issues is a great way to do that! Thanks!
